name: nike
description: A Flutter package.

environment:
  sdk: ">=2.12.0 <4.0.0" # Ensure null safety support


dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
