name: nike
description: A custom Flutter package for various utilities.
version: 1.0.0
homepage: https://github.com/VigneshSSN26/Nike

environment:
sdk: "3.7.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
